.github/workflows/publish_vscode_plugin.yml, publish_scripts/publish_vscode_plugin.py
>Automated the publishing vscode plugin to vscode marketplace.
> 
- Customizing the URL using release version tag and download the .vsix file for the workplace to publish.
- The GitHub action triggers when new release happen using publish 
>Using GitHub action workflow for automating the publishing plugin in the vscode marketplace. Used url that link to ballerina.io download page to download relevant .vsix file for publishing. GitHub action triggers when the new release happen by accessing it version tag through latest_release.json file.
Adding a script with publish_vscode_plugin.py for downloading .vsix file.
=> Updated GitHub workflow to publish vscode pulgin

.github/workflows/intellijPluginUpload.yml
use "ref:" to add the required branch or tag to checkout
IntelliJ publish token should be added as a secret.
=> Updated workflow to upload Intellij Plugin

.github/workflows/homebrew-publish.yml, publish_scripts/homebrew-publish.py
> The workflow and the python script added here would be creating a PR to Homebrew/homebrew-core at each new release.
> The latest version of the ballerina release is captured and the homebrew-core/Formula/ballerina.rb file is updated using a script. A PR would be opened in the Homebrew/homebrew-core repo using the Python Github API library.
> There should be a ACCESS_TOKEN variable with public_repo access privileges set in the secrets section of a user who already has forked the [Homebrew/homebrew-core repo](https://github.com/Homebrew/homebrew-core)
=> Add Workflow for Homebrew Publishing

ballerinaByExample/README.md, ballerinaByExample/tools/generate.go
> At the moment we have two folders, in any case one folder is empty. So I have removed those folders and consolidated the output into one. This makes copying the output b.io much easier.
=> Consolidate output to one folder

publish_scripts/homebrew-publish.py
Remove superfluous new lines to fix not-to-style Homebrew formula bump script so that it matches Homebrew's preferred style.
Less to do for Homebrew maintainers when receiving one of your bot's PRs.
N/A
N/A
Fix Homebrew publishing script to adhere to Homebrew's preferred style.
N/A
N/A
N/A - automatic release process tweak
N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? n/a
- Ran FindSecurityBugs plugin and verified report? n/a
-----
- Hey, I'm from the Homebrew team. We got @ballerina-bot's [first PR](https://github.com/Homebrew/homebrew-core/pull/54056) to update the Ballerina version. It had some style errors.
- This …
=> homebrew-publish: Remove superfluous newlines in sha256 and url

ballerinaByExample/tools/generate.go
note $subject
It is not necessary to have this fix as browsers resolve this.
=> Small fix to "Edit on Github" link

release-notes/swan-lake-alpha3-release-note.md
This PR includes updates related to following standard libraries
- HTTP
- WebSocket
- GraphQL
- Email
- TCP
- UDP
- WebSub
- WebSubHub
- NATS
- STAN
- Kafka
- RabbitMq
=> Add standard library content to the release note

release-notes/swan-lake-alpha3-release-note.md
This PR includes updates related to the following standard libraries
- Log
- OS
- Task
- Time
- Cache
- Xmldata
And details related to the removed packages
- jsonutils
- xmlutils
- runtime
- reflect
=> Add standard library DUI  content to the release note

dependabot/resources/connector_list.json
Enable ballerina version auto bump in connector repos
This is to enable auto bump of the `ballerinaLangVersion` specified in gradle.properties file of each connector repositories
> https://github.com/ballerina-platform/ballerina-release/pull/264
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
=> Enable ballerina version auto bump in connectors

dependabot/resources/connector_list.json
Temporarily disable ballerina lang version auto bump for connectors.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
=> [Connectors] Temporarily disable ballerina lang version auto bump

dependabot/resources/connector_list.json
Fix https://github.com/wso2-enterprise/choreo/issues/6309
Enable ballerina-lang version auto bump for connectors
- Enable ballerina-lang version auto bump for connectors
- Remove unnecessary connectors in `connector_list.json` since those connectors don't use ballerina-lang version
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
Earlier this was disabled in https://github.com/ballerina-platform/ballerina-release/pull/512
=> Enable ballerina-lang version auto bump for connectors

dependabot/resources/connector_list.json
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/70
- This is to enable auto bump of the `ballerinaLangVersion` specified in gradle.properties file of Twitter Connector Repo.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
=> Enable ballerina-lang version bump for Twitter Connector

dependabot/resources/module_list.json
> Change the openAPI repository name `ballerina-openapi` into `openapi-tools` .
=> Change the OpenAPI repository name in `module_list.json` file

dependabot/resources/connector_list.json
- Remove ballerinaLang version bump for `azure eventhub` connector since it doesn't require it.
=> Remove bal version bump for azure eventhub

dependabot/resources/module_list.json
Reverts ballerina-platform/ballerina-release#1361
$subject since bots does not have permissions to merge in the new repositories
=> Revert "Add ballerina observe modules"

dependabot/full_build_pipeline_for_updated_stages.py
There will be an error when the https://github.com/ballerina-platform/ballerina-distribution/blob/master/gradle.properties contains stable versions for standard libraries. This fix will build the standard libraries according to stable versions instead of time stamp versions.
=> Fix full build pipeline (updated stages) for stable versions

.github/workflows/create_stage_lang_branch.yml
>Currently user has to create a new ballerina-lang branch from the last updated stage. With this workflow, users can create a new branch from the last updated stage of ballerina-lang into user's forked repo or to ballerina-platform
>Make it easier for users to test full build pipeline for updated stages.
>This will clone the user's forked lang repository (if user runs the workflow in his/her forked release repo) or ballerina-platform lang repository.
Then it will check whether the last updated stage for lang is a stable version or a time stamp version.
if it is a stable version, this workflow will fetch the stable version branch into a new branch. Otherwise it will create a new branch from the commit id. 
Then the locally created new branch will be pushed to either ballerina-platform lang …
=> Create new workflow to create new lang branch (updated stage)

.github/workflows/full_build_pipeline.yml, .github/workflows/full_build_pipeline_for_updated_stages.yml, dependabot/build_stdlibs_for_lang_updates.py, dependabot/full_build_pipeline_for_updated_stages.py
Currently full build and stage build pipelines can be run against the ballerina-lang branches in ballerina-platform only. This will give an option to run against ballerina-lang branches in user's forked repo. Therefore no need to create branches in ballerina-platform/ballerina-lang.
Increase usability of full build and stage build pipelines.
=> Update full build and stage build pipelines

dependabot/resources/extensions.json, dependabot/resources/module_list.json
> Add GraphQL client generation tool to the Ballerina release
Resolves https://github.com/ballerina-platform/graphql-tools/issues/40
> Add GraphQL client generation tool to the Ballerina release
> 
Add GraphQL client generation tool to extensions.json and module_list.json
> Add GraphQL client generation tool
> 
Ballerina Version: 2201.0.1
Operating System: Ubuntu 20.04
Java SDK: 11
=> Add Graphql client generation tool

release-notes/swan-lake-2201.1.0-release-note.md
> Add GraphQL tool Swan Lake 2201.1.0 release note
Resolves https://github.com/ballerina-platform/graphql-tools/issues/49
> Add GraphQL tool Swan Lake 2201.1.0 release note
> Add content to swan-lake-2201.1.0-release-note.md
> Introduced the Ballerina GraphQL tool for client generation in Ballerina, given the GraphQL schema (SDL) and GraphQL queries.
=> Add GraphQL tool Swan Lake 2201.1.0 release note

release-notes/swan-lake-2201.1.0-release-note.md
> Update GraphQL tool Swan Lake 2201.1.0 release note with learn page links
> Update GraphQL tool Swan Lake 2201.1.0 release note
> Update GraphQL tool Swan Lake 2201.1.0 release note with learn page links
=> Update GraphQL tool Swan Lake 2201.1.0 release note

dependabot/resources/connector_list.json
As asyncapi triggers are there separately, we have removed the listener modules from some connectors via https://github.com/wso2-enterprise/choreo/issues/13186.
As a result, these connectors dont require the ballerinaLang version bump anymore. Hence removing them from the list.
=> Disable `ballerinaLang` version bump for selected connectors

.github/workflows/generate-build-time-stats.yml
>  Automate the build time stats generation of samples
> PR includes a workflow implementation to automate build-time stats generation for specified samples scheduled basis and push the stats to the build-time-data folder of build-time-data branch
> 
- Clone nBallerina, Hello_world, Hello_world_service samples from ballerina-lang repo.
- Set-up Ballerina in the runner.
- Build each project with -dump-build-time
- Remove old stats
- Push back the new stats as bot.
=> Introduce a workflow to automate the build-time stats generation for samples

release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> This PR contains the release-note updates on JSON to Ballerina record converter tool changes.
=> Update swan-lake-2201.2.0-release-note to include JSON to Bal converter changes

.github/workflows/daily-full-build-master.yml, .github/workflows/full_build_pipeline.yml, dependabot/build_stdlibs_for_lang_updates.py
This will enable the option to select downstream repository branch (assuming all the standard library have a unique branch) when triggering the workflow in https://github.com/ballerina-platform/ballerina-release/actions/workflows/full_build_pipeline.yml
To test new features with the full build pipeline.
Fixes #2128
=> Select downstream repo branch in full build pipeline

release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Remove Packages section from Update 3 release note 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
=> Remove Packages section from Update 3 release note

.github/workflows/daily-full-build-2201.3.x.yml, dependabot/build_stdlibs_for_lang_updates.py, dependabot/full_build_pipeline_for_updated_stages.py, dependabot/resources/full_build_ignore_modules.json
This PR will include downstream repository branch as a config for each module if it is needed to be specified in https://github.com/ballerina-platform/ballerina-release/blob/master/dependabot/resources/full_build_ignore_modules.json.
The structure of full_build_ignore_modules.json will be as follows.
```json
{
"master": {
"test-ignore-modules": [],
"build-ignore-modules": [],
"downstream-repo-branches": {}
},
"patch_branch_level1": {
"test-ignore-modules": ["module_name1"],
"build-ignore-modules": ["module_name1"],
"downstream-repo-branches": {
"module_name1": "branch_name1"
}
},
"patch_branch_level2": {
"test-ignore-modules": ["module_name1"],
"build-ignore-modules": ["module_name1"],
"downstream-repo-branches": {
"module_name1": "branch_name1"
}
}
}
```
=> Include downstream repo branch as a config

.github/workflows/full_build_pipeline.yml, dependabot/full_build_pipeline.py
This script has the capability of many things more than the existing two scripts for full build pipeline. It can be used locally as well to debug full build pipeline failures.
The following flags will enable different features of the script.
`--lang-branch` - Pass ballerina-lang branch to use for the builds (If it is not specified, master branch will be used as the default branch)
`--lang-version` - Pass ballerina-lang version to use for the builds (If this argument passes, `--lang-branch` argument won\'t work)
`--downstream-branch` - Pass branch to build the downstream modules. (If the branch not found, the default branch (or branch specified in ignore modules json file) will be used)
`--update-stdlib-dependencies` - Replace all the standard library dependent versions with 'SNAPSHOT' …
=> Include new pipeline with logs

.github/workflows/daily-full-build-2201.3.x.yml, .github/workflows/daily-full-build-2201.4.x.yml, .github/workflows/daily-full-build-2201.5.x.yml, dependabot/full_build_pipeline.py
This will divide daily full builds into 3 separate jobs (build ballerina-lang, build standard libraries & tools, build distribution).
Run daily full builds without exceeding the time limit of 6 hours per each job.
=> Divide daily full build pipeline into 3 separate jobs

dependabot/full_build_pipeline.py
debugger-integration tests are failing intermittently in FBP and this will skip the tests temporary.
=> Skip debugger integration tests in ballerina-lang in FBP

dependabot/resources/full_build_ignore_modules.json
Ignore math.vector module in ballerina 2201.3.x distribution
Fixes: https://github.com/wso2-enterprise/choreo/issues/21394
=> Ignore math.vector module in ballerina 2201.3.x distribution

dependabot/resources/module_list.json
$subject
This is done in order to fix the PR workflow failures happen due to the addition of `module-ballerinax-persist.googlesheets` repository.
=> Remove persist.googlesheets from the modulelist.json

.github/workflows/daily-full-build-2201.3.x.yml, .github/workflows/daily-full-build-2201.4.x.yml, .github/workflows/daily-full-build-2201.5.x.yml, .github/workflows/daily-full-build-2201.6.x.yml
When nBallerina updates its jBallerina dependencies it potentially makes itself unusable as a test target for older versions of jBallerina. Therefore moving forward nBallerina will tag the last commit it has tested to work with a given major version of jBallerina before updating.
=> Fix nBallerina build failures

.github/workflows/trigger-ballerinax-connectors-build.yml
$subject to avoid having conflicts with the graalVM builds, which were getting triggered at the same time.
=> Update trigger time of the ballerinax connectors full build workflow

.github/workflows/code-cov.yml, .github/workflows/daily-full-build-2201.10.x.yml, .github/workflows/daily-full-build-2201.3.x.yml, .github/workflows/daily-full-build-2201.4.x.yml, .github/workflows/daily-full-build-2201.5.x.yml, .github/workflows/daily-full-build-2201.6.x.yml, .github/workflows/daily-full-build-2201.7.x.yml, .github/workflows/daily-full-build-2201.8.x.yml, .github/workflows/daily-full-build-2201.9.x.yml, .github/workflows/daily-full-build-master.yml, .github/workflows/full_build_pipeline.yml, .github/workflows/full_build_pipeline_for_updated_stages.yml
GitHub has deprecated the artifact action v1 and v2 which leads to build failures in release workflows.
https://github.com/ballerina-platform/ballerina-release/actions/runs/10826921877/job/30038931866
**Deprecation notice:**  https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions
=> Update the deprecated artifact action version to v4
