ballerina-platform/ballerina-release

- .github/workflows/api-docs_automation.yml
Automate the api-docs update of the ballerina website when a new version is released
- Clone and add the ballerina folder from the zip to <version>/learn/api-docs/ folder on the branch automate-api-docs-update.
- Automate the pull request to ballerina-dev-website repo
1. Download the api-docs/ballerina folder to github/workspace using svn command(For now ballerina-dev-website/v1-1/learn/api-docs/ballerina folder is considered as the source folder).
2. Clone the ballerina-dev-website repo to github/workspace.
3. Checkout to automate-api-docs-update branch
4. Sync automate-api-docs-update with master
5. Cp ballerina folder to v1-2/learn/api-docs
6. Commit and push the branch to remote
7. Open a pull request to ballerina-dev-website from the branch
> New workflow file to automate the api-docs update

- .github/workflows/ballerina-by-example.yml
- ballerinaByExample/README.md
- ballerinaByExample/build-bbe.sh
- ballerinaByExample/tools/generate.go
> Is to do the $subject. This workflow will run the bbe gen tool and make the generated artifacts available to download.
> Add github workflow for BBE generation

- .github/workflows/ballerina-by-example.yml
> Change the trigger of BBE workflow

- publish_scripts/publish_json.py
> Remove unwanted module

- .github/workflows/ballerina-by-example.yml
> Update version to the latest

- .github/workflows/ballerina-by-example.yml
- ballerinaByExample/build-bbe.sh
> With this new change tool can also be run by giving matedata.json as an argument. This is needed for automation. Sample command is as follows.
`./build-bbe.sh _data/metadata.json`
> Improve the tool support dynamic version

- ballerinaByExample/build-bbe.sh
> Folder structure in b.io has changed from v1-1 to 1.1. This PR is to address that.
> Change the folder name to reflect the new changes

- ballerinaByExample/README.md
- ballerinaByExample/build-bbe.sh
- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/tools/all-bbes.json
- ballerinaByExample/tools/generate.go
This will add BBE gen support for latest with the redirection support.
> Add BBE gen support for latest

- .github/workflows/ballerina-by-example.yml
> Update BBE workflow to generate 1.1.4 BBE artifacts

- ballerinaByExample/README.md
- ballerinaByExample/build-bbe.sh
- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/tools/all-bbes.json
- ballerinaByExample/tools/generate.go
This will remove the template fix for the latest version.
> Remove template fix for latest version

- ballerinaByExample/README.md
- ballerinaByExample/build-bbe.sh
- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/tools/all-bbes.json
- ballerinaByExample/tools/generate.go
This will add support for the gen tool to generate BBE for the latest version or older version on demand...
> Fix gen tool to generate latest and version docs

- ballerinaByExample/templates/example-temp.tmpl
This will remove the extra space added after the permalink of the generated BBE.
> Fix template adding a space at end of the permalink

- ballerinaByExample/README.md
> Add the new mode to the documentation

- apiDocRedirectionModifier/README.md
- apiDocRedirectionModifier/addFrontMatter.go
- apiDocRedirectionModifier/redirection.sh
- apiDocRedirectionModifier/templates/api-doc.tmpl
This will add the API doc redirection modifier tool into this repo.
> Add API doc redirection modifier tool

- ballerinaByExample/README.md
- ballerinaByExample/build-bbe-wf.sh
> This BBE tool is a new addition which pulls the BBEs from dev to build the BBEs.
> Add a new version of BBE tool

- apiDocRedirectionModifier/addFrontMatter.go
This will fix the API docs modifier path issue....
> Fix api doc modifier path issue

- ballerinaByExample/build-bbe-wf.sh
> At the moment script continues to run even if there are errors.
> Add error handling to BBE script

- .github/workflows/ballerina-by-example.yml
> Fix BBE workflow failure

- ballerinaByExample/build-bbe-wf.sh
- ballerinaByExample/build-bbe.sh
- ballerinaByExample/tools/generate.go
> Remove hard-coded values and simplify the usage.
> Improve BBE gentool

- ballerinaByExample/tools/generate.go
> Update repo link

- ballerinaByExample/tools/generate.go
> Do some minor fixes to ballerinaByExample tool

- ballerinaByExample/templates/index-temp.tmpl
- ballerinaByExample/tools/generate.go
Update custom CSS for BBE listing page
> Update custom CSS for BBE listing page

- .github/workflows/ballerina-test-installers.yml
- test-scripts/ballerina-test-automation/build.gradle
- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/src/main/java/io/ballerina/test/Utils.java
- test-scripts/ballerina-test-automation/src/main/java/io/ballerina/test/Windows.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/TestUtils.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/UpdateToolTest.java
- test-scripts/ballerina-test-automation/src/test/resources/testng.xml
> Include Swan lake support

- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/TestUtils.java
> Bump version to swan lake preview 2

- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/tools/generate.go
* https://github.com/ballerina-platform/ballerina-dev-website/issues/1194
* https://github.com/ballerina-platform/ballerina-dev-website/issues/1112
> BBE Tool Improvements

- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/templates/example.tmpl
- ballerinaByExample/tools/generate.go
* https://github.com/ballerina-platform/ballerina-dev-website/issues/1257
* https://github.com/ballerina-platform/ballerina-dev-website/issues/1255
> BBE Tool Fixes

- ballerinaByExample/tools/generate.go
> Fix Code Copy Functionality

- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/templates/example.tmpl
Remove onLoad highlighting in the Gen Tool BBE templates and enable the "Copy" button CSS in the templates.
> Link to the PR for …
> Adding the Copy Button for BBEs

- ballerinaByExample/tools/generate.go
* Fix for Ballerina source code multiple line breaks getting converted to a single line having all the content
* https://github.com/ballerina-platform/ballerina-dev-website/issues/1461
> Fix BBE Copy Issue

- ballerinaByExample/tools/generate.go
> Update copy logic to contain the full source code contents

- .github/workflows/ballerina-website-generation.yml
> Update website generation trigger event
> Update website generation trigger event

- test-scripts/ballerina-test-automation/build.gradle
- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/CentralTest.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/FetchDependencyTest.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/TestUtils.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/UpdateDistTest.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/UpdateToolTest.java
- test-scripts/ballerina-test-automation/src/test/resources/testng.xml
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/26901 …
> Implement dependency fetch tests

- test-scripts/ballerina-test-automation/build.gradle
- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/ProjectTest.java
- test-scripts/ballerina-test-automation/src/test/java/io/ballerina/test/TestUtils.java
- test-scripts/ballerina-test-automation/src/test/resources/testng.xml
> $title
Fixes https://github.com/ballerina-platform/ballerina-release/issues/56 …
> Add test project which supports new project API

- .github/workflows/ballerina-test-installers.yml
> Disable installer tests

- coverage-reports/build.gradle
- coverage-reports/gradle.properties
> Add ballerina lang dependencies
> Add ballerina lang dependencies

- coverage-reports/build.gradle
> Add maven repo for ballerina-lang artifacts
> Add maven repo for ballerina-lang artifacts

- .github/workflows/code-cov.yml
> Create code-coverage.yml workflow
> Create code-coverage.yml workflow

- .gitignore
- coverage-reports/build.gradle
- coverage-reports/gradle.properties
> Generate Coverage Report for Stdlib Modules

- .github/workflows/code-cov.yml
> Add missing entries to code-cov.yml
> Add missing entries to code-cov.yml

- coverage-reports/build.gradle
> Update the exec dependencies for lang repo
> Update the exec dependencies for lang repo

- .github/workflows/code-cov.yml
> Fix wrong code coverage archive path
> Fix wrong code coverage archive path

- .github/workflows/code-cov.yml
> Remove unnecessary zipping step
> Remove unnecessary zipping step

- .github/workflows/code-cov.yml
> Update artifact zip structure
> Update artifact zip structure

- .github/workflows/ballerina-test-installers.yml
> Enable ubuntu build

- ballerinaByExample/templates/index-temp.tmpl
Change the BBE index page layout. …
> Change the BBE Index Page Layout

- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/installer-test/build.gradle
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/InstallerTest.java
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/ProjectTest.java
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
- test-scripts/ballerina-test-automation/update-tool-test/build.gradle
- test-scripts/ballerina-test-automation/update-tool-test/src/test/java/io/ballerina/tool/test/FetchDependencyTest.java
- test-scripts/ballerina-test-automation/update-tool-test/src/test/java/io/ballerina/tool/test/UpdateToolTest.java
> Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/80 …
> Support alpha beta versions

- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/tools/generate.go
> Add functionality to populate metatags content

- ballerinaByExample/tools/generate.go
> Fix in BBE redirects for Swan Lake

- test-scripts/ballerina-test-automation/installer-test/src/test/resources/testng.xml
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/MacOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/80 and https://github.com/ballerina-platform/ballerina-release/issues/62
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
> Fix test automation for mac

- ballerinaByExample/tools/generate.go
> Add functionality to not skip BBE if metatags are not available

- .github/workflows/ballerina-test-installers.yml
> Seperate installer and update tool tests
> Separate installer and update tool tests

- ballerinaByExample/tools/generate.go
> Fix https://github.com/ballerina-platform/ballerina-dev-website/issues/1875

- test-scripts/ballerina-test-automation/gradle.properties
> Update testing version to alpha2
> Update testing version to alpha2

- test-scripts/ballerina-test-automation/gradle.properties
> Bump tool version

- release-notes/swan-lake-alpha3-release-note.md
> Add xml:Text() and annotations change

- release-notes/swan-lake-alpha3-release-note.md
Add release note for [module-level public variable declaration](https://github.com/ballerina-platform/ballerina-lang/pull/28926) and [module-level complex variable declaration](https://github.com/ballerina-platform/ballerina-lang/pull/27824).
> Add release note for module level public and complex variables

- release-notes/swan-lake-alpha3-release-note.md
This PR will update the release note with conditional breakpoint support.
> Update release note with conditional breakpoints support

- release-notes/swan-lake-alpha3-release-note.md
> Add equality restriction for readonly change

- release-notes/swan-lake-alpha3-release-note.md
> Update release notes with Ballerina Shell changes

- release-notes/swan-lake-alpha3-release-note.md
> Update release note with any function type

- release-notes/swan-lake-alpha3-release-note.md
> Include Dev Tools release notes
> Include Dev Tools release notes

- release-notes/release-note-template.md
- release-notes/swan-lake-alpha3-release-note.md
Add the Swan Lake release note Template. …
> Add the Swan Lake Release Note Template

- release-notes/swan-lake-alpha3-release-note.md
> Add notes to setup auto-completion for mac bash

- release-notes/swan-lake-alpha3-release-note.md
> Change the stdlib sub topics to point format

- release-notes/swan-lake-alpha3-release-note.md
> Add langserver crash reporting support for the release note …
> Add langserver crash reporting support for the release note

- release-notes/swan-lake-alpha3-release-note.md
> Add the improvements to the bindgen tool in the release note

- release-notes/swan-lake-alpha3-release-note.md
> Update tcp secureSocket code in alpha3-release-note.md

- release-notes/swan-lake-alpha3-release-note.md
> Add rename changes to udp and tcp module

- release-notes/swan-lake-alpha3-release-note.md
> Update Alpha 3 release note with Runtime changes

- release-notes/swan-lake-alpha3-release-note.md
> Fix title levels of stdlib content

- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-release/issues/120 …
> Update tests and bump versions

- release-notes/swan-lake-alpha3-release-note.md
> Add xml breaking changes to release note

- release-notes/release-note-template.md
Improve the Swan Lake release note template. …
> Improve the Swan Lake Release Note Template

- release-notes/swan-lake-alpha4-release-note.md
Create the SLAlpha4 release note. …
> Create the SLAlpha4 Release Note

- dependabot/update_lang_version.py
> Fix script for SNAPSHOT versions

- dependabot/update_lang_version.py
> Improve logs

- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> Bump versions

- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> Add a comment for readability

- release-notes/swan-lake-alpha4-release-note.md
> Add runtime changes to release note

- release-notes/swan-lake-alpha4-release-note.md
> Update the Swan Lake alpha4 release note for language changes

- release-notes/release-note-template.md
- release-notes/swan-lake-alpha4-release-note.md
Reverts ballerina-platform/ballerina-release#134
> Update standard library DUI release note

- release-notes/swan-lake-alpha4-release-note.md
> Update standard library PCP release note

- release-notes/swan-lake-alpha4-release-note.md
> Add test framework improvements to Alpha4 release note

- release-notes/swan-lake-alpha4-release-note.md
> Update SwanLake Alpha4 release notes for debugger

- release-notes/release-note-template.md
Update Release Note template TOC. …
> Update Release Note template TOC

- test-scripts/ballerina-test-automation/gradle.properties
> Update ballerina version

- .github/workflows/update_dependency_graph.yml
> Add environment variables to the actions

- dependabot/update_dependencies_version.py
> Fix indendation

- dependabot/update_dependencies_version.py
> Auto merge feature bug fixes

- dependabot/update_dependencies_version.py
- dependabot/update_version_data.py
> Fix waiting when conclusion of check is not failure or success

- dependabot/update_dependencies_version.py
- dependabot/update_version_data.py
> Ensure the merge commit is build and published before moving to next level

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
- dependabot/update_dependencies_version.py
- dependabot/update_version_data.py
> Add group id and artifact id of modules in the module_list json

- .github/workflows/update_dependency_version.yml
- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
- dependabot/update_dependencies_version.py
- dependabot/update_version_data.py
> Bump dependency version with latest timestamped version

- README.md
- release-notes/swan-lake-alpha5-release-note.md
Add the SLAlpha5 release note. …
> Add the SLAlpha5 Release Note

- release-notes/swan-lake-alpha5-release-note.md
> Update the Swan Lake alpha5 release note for language changes

- release-notes/swan-lake-alpha5-release-note.md
$subject
Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/29937 …
> Update the release note with the standard lib changes

- release-notes/swan-lake-alpha5-release-note.md
> Swan Lake alpha5 release note for runtime changes

- release-notes/swan-lake-alpha5-release-note.md
> Update SwanLake Alpha5 release note for PCM team

- test-scripts/ballerina-test-automation/gradle.properties
> Update ballerina and tool versions
> Update ballerina and tool versions

- dependabot/update_dependencies_version.py
> Fix commit message

- .github/workflows/update_dependency_graph.yml
- .github/workflows/update_dependency_version.yml
> Change dependency bump to noon IST

- .github/workflows/update_dependency_version.yml
> Call scheduled trigger with defaults

- .github/workflows/update_dependency_graph.yml
> Run dependency workflow if modules_list.json is updated

- release-notes/swan-lake-betarc1-release-note.md
Create the Swan Lake Beta RC1 release note. …
> Create the Swan Lake Beta RC1 Release Note

- dependabot/resources/module_list.json
> Disable schedule bump of ballerina lang

- .github/workflows/update_dependency_graph.yml
> Only trigger workflow if master is updated

- .github/workflows/ballerina-by-example.yml
> Change bbe generation to manual trigger

- dependabot/resources/module_list.json
> Change the OpenAPI group ID

- dependabot/update_dependencies_version.py
> Run auto bump check before workflow file is updated

- dependabot/update_dependencies_version.py
> Mark not updated module as build success

- .github/workflows/ballerina-test-installers.yml
> Ignore installer tests in automated branches

- dependabot/update_dependencies_version.py
> Fix syntax error

- dependabot/resources/module_list.json
- dependabot/update_dependencies_version.py
- dependabot/update_version_data.py
> Introduce regex to differenciate latest lang version

- .github/workflows/ballerina-test-installers.yml
> Ignore status dashboard update in installer tests

- dependabot/resources/module_list.json
> Disable auto bump temporarily

- dependabot/resources/module_list.json
> Enable scheduled version bumps

- .github/workflows/update_connectors.yml
> Fix calling wrong script

- .github/workflows/update_dependency_version.yml
> Update input description

- .github/workflows/ballerina-test-installers.yml
> Ignore build checks for automated branches

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
> Fix Update Status Dashboard workflow error

- dependabot/update_dependencies_in_pipeline.py
> Fix checks passing even before the builds are triggered

- .github/workflows/update_dependency_version.yml
> Fix Update Ballerina Language Version workflow error

- dependabot/update_dependencies_in_pipeline.py
> Fix check of pr builds

- dependabot/update_dependencies_in_pipeline.py
> Add links to the repository status chat notification

- release-notes/swan-lake-beta1-release-note.md
> Add Standard Lirbrary PCM Team Release Notes

- dependabot/utils.py
> Fix remote file lookup

- dependabot/notify_chat.py
- dependabot/utils.py
> Fix chat message logic

- dependabot/update_lag_status.py
- dependabot/utils.py
> Fix readme not being updated

- dependabot/update_dependencies_in_pipeline.py
> Improve chat message

- release-notes/swan-lake-beta1-release-note.md
> Add stdlib DUI changes to beta1 release note

- dependabot/update_dependencies_in_pipeline.py
> Fix chat message url

- ballerinaByExample/templates/example-temp.tmpl
Add the `active` property to the BBE front matter. …
> Add the `active` Property to the BBE Front Matter

- dependabot/notify_chat.py
- dependabot/update_lag_status.py
> Fix notification send param check

- .github/workflows/update_connectors.yml
- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/notify_chat.py
> Remove redundant if condition

- dependabot/update_connectors.py
> Fix connector update script timing out

- dependabot/update_connectors.py
> Fix key not found in logs

- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/tools/generate.go
> Add Active to Front Matter and Stop Skipping No BAL BBEs

- release-notes/swan-lake-beta1-release-note.md
> Add debugger release notes for SL Beta1

- dependabot/notify_chat.py
- dependabot/update_lag_status.py
> Remove central only modules in chat notification

- release-notes/swan-lake-beta1-release-note.md
Adds `@cloud:Expose` annotation to support custom listeners. …
> Add cloud expose annotation to release note

- ballerinaByExample/tools/generate.go
Enable skipping BBEs with no BAL files. …
> Enable Skipping BBEs with No BAL Files

- release-notes/swan-lake-beta1-release-note.md
> Add runtime changes to beta 1 release note

- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_lag_status.py
> Improve notification with more details

- test-scripts/ballerina-central/tests/alpha2/init-gh.bats
- test-scripts/ballerina-central/tests/beta1/init-gh.bats
- test-scripts/ballerina-central/tests/run-tests.sh
> Fix test cases for beta1 release

- test-scripts/ballerina-central/Dockerfile
- test-scripts/ballerina-central/tests/alpha2/init-gh.bats
- test-scripts/ballerina-central/tests/beta1/init-gh.bats
- test-scripts/ballerina-central/tests/beta1/pull-gh.bats
- test-scripts/ballerina-central/tests/beta1/pull-latest-gh.bats
- test-scripts/ballerina-central/tests/beta1/push-gh.bats
- test-scripts/ballerina-central/tests/beta1/search-gh.bats
- test-scripts/ballerina-central/tests/run-tests.sh
> Add beta1 central tests

- dependabot/resources/module_list.json
> Enable daily update of dependencies

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/update_lag_status.py
> Update workflows to send notification only from a schedule

- .github/workflows/delete-package.yml
> Update delete-package.yml package description

- .github/workflows/ballerina-test-installers.yml
- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/installer-test/build.gradle
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/CentOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/MacOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Ubuntu.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-release/issues/493 …
> Improve update tool tests

- .github/workflows/ballerina-test-installers.yml
> Fix syntax error in yaml file

- .github/workflows/ballerina-test-installers.yml
- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/installer-test/build.gradle
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/CentOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/MacOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Ubuntu.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> Improve workflow to support staging and prod

- .github/workflows/ballerina-test-installers.yml
- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/installer-test/build.gradle
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/CentOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/MacOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Ubuntu.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> Improve workflow for test automation

- .github/workflows/ballerina-test-installers.yml
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/CentOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/MacOS.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Ubuntu.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
> $title
Fixes https://github.com/ballerina-platform/ballerina-release/issues/493 …
> Improve work flows and refactor code

- .github/workflows/ballerina-central-test-on-dev-schedule.yml
> Change access token for central integration tests

- ballerinaByExample/build-bbe.sh
- ballerinaByExample/tools/generate.go
> Enable Adding Images to BBEs

- dependabot/resources/module_list.json
> Update substring as beta2

- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_lag_status.py
> Disable notifications for observability modules

- release-notes/release-note-template.md
- release-notes/swan-lake-beta2-release-note.md
Add the Swan Lake Beta2 release note. …
> Add the Swan Lake Beta2 Release Note

- test-scripts/ballerina-test-automation/gradle.properties
- test-scripts/ballerina-test-automation/installer-test/build.gradle
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/ProjectTest.java
- test-scripts/ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java
- test-scripts/ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Windows.java
- test-scripts/ballerina-test-automation/update-tool-test/build.gradle
- test-scripts/ballerina-test-automation/update-tool-test/src/test/java/io/ballerina/tool/test/FetchDependencyTest.java
- test-scripts/ballerina-test-automation/update-tool-test/src/test/java/io/ballerina/tool/test/UpdateDistTest.java
- test-scripts/ballerina-test-automation/update-tool-test/src/test/java/io/ballerina/tool/test/UpdateToolTest.java
> $title 
Fixes https://github.com/ballerina-platform/ballerina-release/issues/63 and  https://github.com/ballerina-platform/ballerina-update-tool/issues/80 …
> Fix the issues in ballerina-test-automation for Windows

- dependabot/resources/module_list.json
> Move modules not packed in distribution to central only modules

- release-notes/swan-lake-beta2-release-note.md
Since Azure, Lambda or Docker doesn't contain any significant bug fixes or improvements, it'll be removed from the release notes. …
> Remove c2c repos with no changes

- dependabot/resources/module_list.json
Reverts ballerina-platform/ballerina-release#589
> Revert "Move modules not packed in distribution to central only modules"

- ballerinaByExample/templates/ballerina-io.css
- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/templates/example.tmpl
> Table template create issues on UI, the issue fix with div and styled flexbox
>Fixes #2464
>Fixes #2457
> Table Layout Converted to Div Layout

- ballerinaByExample/templates/example-temp.tmpl
> Remove Unwanted Tables

- ballerinaByExample/templates/example-temp.tmpl
> Add Missing Code {{range  $i, $element := .Segs}}
> Add Missing Code

- test-scripts/ballerina-test-automation/gradle.properties
> Update Swan Lake version

- test-scripts/ballerina-central/Dockerfile
- test-scripts/ballerina-central/tests/run-tests.sh
> Enable beta2 tests for ballerina central

- release-notes/swan-lake-beta2-release-note.md
> Update SwanLake Beta 2 release notes with debugger changes

- release-notes/swan-lake-beta2-release-note.md
> Add runtime related changes to beta 2 release note

- release-notes/swan-lake-beta2-release-note.md
> Update SwanLake Beta 2 release notes with recursive tuple type changes 

- release-notes/swan-lake-beta2-release-note.md
Update SwanLake Beta 2 release notes with Testerina changes …
> Update SwanLake Beta 2 release notes with Testerina changes

- release-notes/swan-lake-beta2-release-note.md
> Add about String Iterator fix

- release-notes/swan-lake-beta2-release-note.md
> Update the release note with StdLib PCP content

- release-notes/swan-lake-beta2-release-note.md
> Add the bindgen improvements to the Beta2 release note

- release-notes/swan-lake-beta2-release-note.md
> Add improvements for the testframework to the Beta2 release note

- test-scripts/ballerina-test-automation/gradle.properties
> Bump update tool version

- release-notes/swan-lake-beta2-release-note.md
> Address runtime release note suggestions

- ballerinaByExample/templates/example-temp.tmpl
- ballerinaByExample/templates/index-temp.tmpl
> Update reference by examples

- ballerinaByExample/templates/example-temp.tmpl
> Add Div Structure for Table
>Fixes #2508
> Add Div Structure for Table

- ballerinaByExample/templates/example-temp.tmpl
> Add Parameter to URL "is_ref_by_example=true"
> Add Parameter to URL "is_ref_by_example=true"

- dependabot/update_dependencies_in_pipeline.py
> Fix update script considering update of stable version

- dependabot/resources/module_list.json
- dependabot/update_lag_status.py
> Fix dashboard considering update of stable version

- ballerinaByExample/templates/index-temp.tmpl
Revert the "Reference By Examples" Term from 1.2.x BBE index page. …
> Revert the "Reference By Examples" Term from 1.2.x

- ballerinaByExample/templates/index-temp.tmpl
> Add learn by examples link to BBE index page

- ballerinaByExample/templates/index-temp.tmpl
Add a full stop to the Learn By Examples link. …
> Add a Full Stop to the "Learn By Examples" Link

- ballerinaByExample/build-bbe.sh
- ballerinaByExample/tools/generate.go
> Remove images folder

- test-scripts/ballerina-central/tests/run-tests.sh
> Update test for beta1 package restriction in ballerina central

- .github/workflows/ballerina-test-installers.yml
> Fix installer test workflow

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/resources/module_list.json
- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_dependency_graph.py
- dependabot/update_lag_status.py
- dependabot/utils.py
$subject
Fixes https://github.com/ballerina-platform/ballerina-release/issues/655
> Add code owners to the notification

- dependabot/resources/module_list.json
> Bump lang version to beta3

- dependabot/resources/module_list.json
- dependabot/update_dependency_graph.py
> Change default group id of the modules

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/resources/module_list.json
Partially fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1593
> Add MSSQL module to update pipeline

- dependabot/utils.py
> Fix notification formatting

- .github/workflows/update_dependency_version.yml
- dependabot/resources/module_list.json
- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_dependency_graph.py
> Add support to override sending failure notification

- dependabot/resources/module_list.json
$subject since these are not mandatory for the distribution build
> Move ballerinax modules to the end of the pipeline

- dependabot/update_lag_status.py
> Improve dashboard titles

- dependabot/update_dependencies_in_pipeline.py
> Fix script proceeding when there is a PR failure

- dependabot/resources/module_list.json
> Override group id for transaction module

- dependabot/update_dependencies_in_pipeline.py
> Fix workflow continuing even in failure

- dependabot/update_dependencies_in_pipeline.py
> Fix syntax

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/resources/module_list.json
- dependabot/update_dependency_graph.py
> Streamline user id env variables

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/resources/module_list.json
- dependabot/update_dependency_graph.py
Reverts ballerina-platform/ballerina-release#751
> Revert "Streamline user id env variables"

- dependabot/utils.py
> Fix regex for sanitising chat message for print

- dependabot/resources/module_list.json
- dependabot/update_dependencies_in_pipeline.py
> Enable auto update of lang version

- dependabot/update_dependencies_in_pipeline.py
> Improve notification

- dependabot/update_dependencies_in_pipeline.py
> Improve chat message formatting

- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_lag_status.py
> Fix formatting in lag button

- test-scripts/ballerina-central/tests/run-tests.sh
> Enable standard libs for ballerina central beta2 push and pull integration tests

- dependabot/update_dependencies_in_pipeline.py
> Fix wait logic for distribution

- dependabot/update_dependencies_in_pipeline.py
> Improve notification to skip trigger warning for final level modules

- dependabot/update_dependencies_in_pipeline.py
> Re-approve PR always due to dismissing stale reviews

- dependabot/update_dependencies_in_pipeline.py
> Fix notification to include trigger message for distribution build

- ballerinaByExample/templates/index-temp.tmpl
Add keywords to the index page for searching. This will fix https://github.com/ballerina-platform/ballerina-dev-website/issues/2610.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Add keywords to the index page for searching

- release-notes/swan-lake-beta3-release-note.md
$title. Compiled by the compiler team.
> Add release note content for SL Beta3 language changes

- release-notes/swan-lake-beta3-release-note.md
> Add runtime changes to beta 3 release note

- release-notes/swan-lake-beta3-release-note.md
> Add bullet list to config type list

- release-notes/swan-lake-beta3-release-note.md
> Add c2c improvements to beta3 release note

- release-notes/swan-lake-beta3-release-note.md
This PR will add beta 3 debugger release note.
> Add Beta 3 debugger release note

- release-notes/swan-lake-beta3-release-note.md
Added new dependency management changes
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Added dependency management changes

- release-notes/swan-lake-beta3-release-note.md
> Add `Relaxed Query Expression Keywords` section to SLB3 release note

- release-notes/swan-lake-beta3-release-note.md
Update release note along with the new feature addition related to [1] [2].
[1] https://github.com/ballerina-platform/ballerina-standard-library/issues/1716
[2] https://github.com/ballerina-platform/ballerina-standard-library/issues/1788
> Update release note with OAuth2 JWT bearer grant support

- .github/workflows/update_stdlib_dependency_graph.yml
- dashboard/index.html
- dashboard/stdlib_graph.gv
- dependabot/update_stdlib_dependency_graph.py
Create stdlib_graph.dot file and visualize via dashboard/index.html
Currently the stdlib modules are ordered by level by level. Using a graph which is created based on dependency modules, it reduces PR lags in the standard library modules.
#923
> Create Stdlib Dependency Graph

- release-notes/swan-lake-beta3-release-note.md
> Add gRPC tool related changes to relase note

- dependabot/resources/module_list.json
> Add protobuf module to dependency update pipline

- dependabot/resources/module_list.json
- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_dependency_graph.py
- dependabot/update_lag_status.py
> Improve extended library flag configuration

- release-notes/swan-lake-beta3-release-note.md
> Update release note for type narrowing change

- dependabot/resources/module_list.json
> Temporarily disable daily version updates

- release-notes/swan-lake-beta3-release-note.md
> Remove runtime api changes from release note

- ballerinaByExample/templates/example-temp.tmpl
Fix copying code snippet contents twice to clipboard in ballerina learn by example pages in ballerina website.
https://github.com/ballerina-platform/ballerina-dev-website/issues/2609
> Fix copying code snippet contents twice to clipboard

- dependabot/update_stdlib_dependency_graph.py
Use utils commit_file and open_pr_and_merge methods
> Change branch for PR

- .github/workflows/update_stdlib_dependency_graph.yml
- dependabot/update_stdlib_dependency_graph.py
Use utils commit_file and open_pr_and_merge methods
Fix Automated PR workflow for stdlib dependency graph which has been broken.
> Fix Automated PR workflow for stdlib dependency graph

- release-notes/swan-lake-beta3-release-note.md
> Add new runtime apis to release note

- .github/workflows/stdlib_build_test_on_ballerina_lang_PRs.yml
- dependabot/build_stdlibs_for_lang_updates.py
Reduce build failures happen in standard library modules due to changes in ballerina-lang
> Create workflow for standard library build test for ballerina-lang PRs

- test-scripts/ballerina-central/Dockerfile
- test-scripts/ballerina-central/tests/beta3/init-gh.bats
- test-scripts/ballerina-central/tests/run-tests.sh
> Enable beta3 related central push and pull tests

- release-notes/swan-lake-beta3-release-note.md
> Update the release notes with GraphQL changes

- release-notes/swan-lake-beta3-release-note.md
> Add sql error types improvement to release note

- release-notes/swan-lake-beta3-release-note.md
> Update OpenAPI improvements

- release-notes/swan-lake-beta3-release-note.md
> Add missing websocket features to release note

- release-notes/swan-lake-beta3-release-note.md
> Update release note with HTTP changes

- dependabot/build_stdlibs_for_lang_updates.py
To build a full build pipeline for ballerina including standard library modules and ballerina-distribution.
> Add ballerina-distribution to build pipeline workflow

- dependabot/update_dependencies_in_pipeline.py
> Increase script timeout for level 6 builds

- release-notes/swan-lake-beta3-release-note.md
> Add log module related changes to release notes

- release-notes/swan-lake-beta3-release-note.md
> Update SL beta3 debugger changes

- release-notes/swan-lake-beta3-release-note.md
> Add FTP module related changes to the release note
> Add FTP module related release note content

- release-notes/swan-lake-beta3-release-note.md
> Add GraphQL Context Support Information to the Release Note

- release-notes/swan-lake-beta3-release-note.md
> Update SQL module release notes

- dependabot/resources/module_list.json
> Enable auto bump

- .github/workflows/notify-connector-failures.yml
> Fix python file path

- .github/workflows/stdlib_build_test_on_ballerina_lang_PRs.yml
- dependabot/build_stdlibs_for_lang_updates.py
Give option to the developers to run the build pipeline workflow with or without tests.
https://github.com/ballerina-platform/ballerina-release/issues/1271
> Add flag to enable/disable tests in build-pipeline workflow

- release-notes/swan-lake-beta4-release-note.md
> Update beta4 release notes with new debugger features

- .github/workflows/update_connectors.yml
- .github/workflows/update_dependency_graph.yml
Add python package installation for encryption.
> Add python package installation

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/resources/module_list.json
- dependabot/update_dependency_graph.py
> Remove unnecessary configuration

- release-notes/swan-lake-beta4-release-note.md
Add disallowing intervening whitespaces in qualified identifier to release note.
> Add qualified identifier changes and new reserved keywords to the release note

- release-notes/swan-lake-beta4-release-note.md
> Fix description

- dependabot/update_user_id.py
> Fix csv read

- .github/workflows/update_dependency_version.yml
> Stop in-progress dependency action when a new workflow is started

- release-notes/swan-lake-beta4-release-note.md
> Improve examples in the release note

- dependabot/update_dependencies_in_pipeline.py
> Wait for codecov checks before auto merge

- dependabot/update_dependencies_in_pipeline.py
> Skip codecov check for ballerina-distribution

- release-notes/swan-lake-beta4-release-note.md
> Update standard library DIU Beta 4 release notes

- .github/workflows/full_build_pipeline.yml
Add Installer generation to full build pipeline
Build full pipeline including installers
> Add Installer generation to full build pipeline

- release-notes/swan-lake-beta4-release-note.md
> Add record optional field section

- dependabot/update_dependencies_in_pipeline.py
> Fix script waiting in endless loop for distribution pr status check

- release-notes/swan-lake-beta4-release-note.md
> Add runtime changes to beta 4 release note

- release-notes/swan-lake-beta4-release-note.md
> Add numeric literal changes to beta 4 release note

- release-notes/swan-lake-beta4-release-note.md
$subject to add the note on new feature
> Add document symbol feature release note for Language Server

- release-notes/swan-lake-beta4-release-note.md
> Add gRPC new features for the SLbeta4 release note

- release-notes/swan-lake-beta4-release-note.md
> Add extended capability feature note

- dependabot/build_stdlibs_for_lang_updates.py
Resolve issues in full build pipeline workflow
> Fix lang version differences in full build pipeline

- .github/workflows/full_build_pipeline.yml
Fix the issues in full build pipeline workflow
> Fix path issue in full build pipeline

- dependabot/resources/module_list.json
> Update lang dependency version
> Update lang dependency version

- test-scripts/ballerina-central/Dockerfile
- test-scripts/ballerina-central/tests/alpha5/search-gh.bats
- test-scripts/ballerina-central/tests/beta1/search-gh.bats
- test-scripts/ballerina-central/tests/beta2/search-gh.bats
- test-scripts/ballerina-central/tests/beta3/search-gh.bats
Update test organization used for central tests.
Fixes part of https://github.com/wso2-enterprise/ballerina-registry/issues/1183 …
> Update test organisation used for central tests

- .github/workflows/ballerina-central-test.yml
Update secret key used for access token.  …
> Update secret key used for access token

- test-scripts/ballerina-central/tests/alpha5/search-gh.bats
- test-scripts/ballerina-central/tests/beta1/search-gh.bats
- test-scripts/ballerina-central/tests/beta2/search-gh.bats
- test-scripts/ballerina-central/tests/beta3/search-gh.bats
Fix assertion failure due to character limit change.
[Fixes part of 1183](https://github.com/wso2-enterprise/ballerina-registry/issues/1183)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
> Fix assertion failure due to character limit change

- .github/workflows/ballerina-staging-central-test.yml
- test-scripts/ballerina-central/Dockerfile
- test-scripts/ballerina-central/tests/beta4/init-gh.bats
- test-scripts/ballerina-central/tests/beta4/pull-gh.bats
- test-scripts/ballerina-central/tests/beta4/pull-latest-gh.bats
- test-scripts/ballerina-central/tests/beta4/push-gh.bats
- test-scripts/ballerina-central/tests/beta4/search-gh.bats
- test-scripts/ballerina-central/tests/run-tests.sh
Improve central tests cases.
Fixes https://github.com/wso2-enterprise/ballerina-registry/issues/1187
> Link to the PR for changes …
> Improve central tests cases

- test-scripts/ballerina-central/tests/run-tests.sh
Update central test cases
Fixes https://github.com/wso2-enterprise/ballerina-registry/issues/1187
> Link to the PR for changes to …
> Update central test cases

- dependabot/resources/module_list.json
> Disable scheduled dependency  update temporarily

- dependabot/resources/module_list.json
> Update dependency flow to pick beta6 lang versions

- .github/workflows/notify-build-failures.yml
- dependabot/notify_build_failure.py
Use PyGithub library to access code owners without using the downloaded file from master branch.
Fixes #1473
> Fix CODEOWNERS file access

- release-notes/swan-lake-beta4-release-note.md
- release-notes/swan-lake-beta5-release-note.md
> Add the SLBeta5 Release Note

- ballerinaByExample/README.md
Update Go installation troubleshooting tips. …
> Update Go Installation Troubleshooting Tips

- dependabot/resources/module_list.json
> Temporarily disable scheduled dependency updates

- release-notes/swan-lake-beta5-release-note.md
- release-notes/swan-lake-beta6.md
Create the SLBeta6 release note. …
> Create the SLBeta6 Release Note

- release-notes/swan-lake-beta6-release-note.md
> Update beta6 release note with OpenAPI changes 

- release-notes/swan-lake-beta6-release-note.md
> Update beta 6 release note with HTTP changes

- release-notes/swan-lake-beta6-release-note.md
> Fix grammatically incorrect verb

- release-notes/swan-lake-beta6-release-note.md
> Add unary-plus resulting type change

- test-scripts/ballerina-central/Dockerfile
- test-scripts/ballerina-central/tests/beta6/init-gh.bats
- test-scripts/ballerina-central/tests/beta6/pull-gh.bats
- test-scripts/ballerina-central/tests/beta6/pull-latest-gh.bats
- test-scripts/ballerina-central/tests/beta6/push-gh.bats
- test-scripts/ballerina-central/tests/beta6/search-gh.bats
- test-scripts/ballerina-central/tests/run-tests.sh
> Add beta6 central tests

- .github/workflows/ballerina-central-test-on-dev-schedule.yml
- Add workflow dispatch to Dev central test
> Add workflow dispatch to Dev central test

- dependabot/resources/module_list.json
> Update lang version

- dependabot/update_dependencies_in_pipeline.py
> Fix lang version timestamp processing

- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_lag_status.py
> Fix dashboard script due to lang version change

- .github/workflows/update_dependency_version.yml
$subject
This ensure, parallel jobs from different branches can be run.
> Fix concurrency group name

- dependabot/resources/module_list.json
Adding `module-ballerina-observe` and `module-ballerinai-observe`
- https://github.com/ballerina-platform/ballerina-lang/issues/33195
> Add ballerina observe modules

- dependabot/resources/module_list.json
- dependabot/utils.py
> Fix script failure when codeowners file is not available

- dependabot/update_lag_status.py
> Add i postfix for internal modules

- dependabot/resources/module_list.json
Adding `module-ballerina-observe` and `module-ballerinai-observe`
- https://github.com/ballerina-platform/ballerina-lang/issues/33195
> Add observability modules

- dependabot/resources/module_list.json
> Enable auto merge for prometheus and jaeger
> Enable auto merge for prometheus and jaeger

- dependabot/update_dependencies_in_pipeline.py
> Skip wait for ballerina observe codecov

- dependabot/update_user_id.py
> Change file read mode

- dependabot/update_user_id.py
> Change text parsing mode

- .github/workflows/full_build_pipeline.yml
Fixes full build pipeline failures occurred due to version changes
> Fix full build pipeline failures

- .github/workflows/full_build_pipeline_for_updated_stages.yml
- dependabot/full_build_pipeline_for_updated_stages.py
This will build the full pipeline from ballerina-lang to ballerina distribution including standard library modules against a specific branch of ballerina-lang where the developer makes changes.
Apart from that, this will use the standard library stages where the last time ballerina-distribution repository daily-build was passed. Therefore it will reduce the build failures in the full build pipeline.
By using this workflow, developers can check whether their changes on ballerina-lang will break the standard library modules or not. This will reduce the build failures in standard library module repositories as well as ballerina-distribution repository.
Switch to the ballerina-lang branch which has given as an input. 
Last updated version commit ids are read by using …
> Create full build pipeline for updated stages

- release-notes/swan-lake-GA-release-note.md
Add the Swan Lake GA release note. …
> Add the Swan Lake GA Release Note

- README.md
Update extension dependency dashboard
> [Automated] Update Extension Dependency Dashboard

- release-notes/swan-lake-GA-release-note.md
> Add reference for language server bug fixes

- release-notes/swan-lake-GA-release-note.md
> Add gRPC proto path changes to the GA release note

- release-notes/swan-lake-GA-release-note.md
> Add Kafka changes to the release note

- release-notes/swan-lake-GA-release-note.md
> [FIX] Link for language server bug fixes

- release-notes/swan-lake-GA-release-note.md
$Subject. Removed aws and azure functions sections as they dont have any bug fixes. Removed docker as its coupled with c2c. 
> …
> Add code to cloud release notes

- release-notes/swan-lake-GA-release-note.md
> Add GraphQL changes to the release note

- release-notes/swan-lake-GA-release-note.md
> Update Shell new features related to GA

- release-notes/swan-lake-GA-release-note.md
> Update release note with OpenAPI improvements 

- release-notes/swan-lake-GA-release-note.md
$title, as authored offline by the compiler team.
> Add language changes to the SL GA release note

- .github/workflows/sync_lang_master_with_patch.yml
- dependabot/sync_lang_master_with_patch.py
> Add nightly patch branch syncing with master for lang

- .github/workflows/daily-full-build.yml
> To build `full build pipeline` against master branches daily to reduce build failures.
> https://github.com/ballerina-platform/ballerina-lang/issues/35138
> https://github.com/ballerina-platform/ballerina-release/pull/1856
> Create daily full build

- .github/workflows/update_dependency_version.yml
- .github/workflows/update_lag_status_dashboard.yml
- dependabot/resources/module_list.json
> Disable daily workflow trigger for dependency update

- release-notes/swan-lake-2201.0.1-release-note.md
Add the 2201.0.1 (Swan Lake) release note. …
> Add the 2201.0.1 (Swan Lake) Release Note

- dependabot/sync_lang_master_with_patch.py
> Add pull request mergeability check

- release-notes/swan-lake-2201.0.1-release-note.md
> Update 2201.0.1 Release note with Standard Library bug fixes

- dependabot/sync_lang_master_with_patch.py
> Fix automated pr closing

- dependabot/sync_lang_master_with_patch.py
> Add reviewer bot

- dependabot/sync_lang_master_with_patch.py
> Fix pull request head

- .github/workflows/full_build_pipeline.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Fix full build pipeline

- dependabot/resources/module_list.json
> Update lang version substring

- release-notes/swan-lake-2201.0.2-release-note.md
Add the 2201.0.2 (Swan Lake) release note. …
> Add the 2201.0.2 (Swan Lake) Release Note

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> skip distribution tests

- .github/workflows/daily-full-build.yml
- dependabot/build_stdlibs_for_lang_updates.py
> skip lang tests

- delete-packages-scripts/usernames_with_package_delete_access.json
> Give permission access

- dependabot/sync_lang_master_with_patch.py
$title
fixes ballerina-platform/ballerina-lang#35422
> Create a temporary branch for daily syncing PR

- .github/workflows/daily-full-build.yml
- dependabot/build_stdlibs_for_lang_updates.py
Send notifications to chat when there is a build failure
Reduce breaking changes in ballerina-lang
https://github.com/ballerina-platform/ballerina-release/issues/1895
> Add notification to daily full build

- dependabot/build_stdlibs_for_lang_updates.py
> Fix version imcompatibility

- .github/workflows/daily-full-build.yml
- dependabot/notify_full_build_failure.py
> Change notification for full build

- dependabot/notify_full_build_failure.py
> Change notification message

- release-notes/swan-lake-2201.0.3-release-note.md
Add the 2201.0.3 (Swan Lake) release note. …
> Add the 2201.0.3 (Swan Lake) Release Note

- .github/workflows/update_lang_version.yml
- dependabot/update_lang_version.py
Update ballerina-lang version in distribution. 
fixes #1892 
Create a repository_dispatch event at ballerina-lang repo and post the timestamped version to update in ballerina-distribution repo.
> Bump lang version

- .github/workflows/update_lang_version.yml
- dependabot/update_lang_version.py
> Update workflow to handle branch details

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Change flow of full build pipeline (patch)

- release-notes/swan-lake-2201.0.3-release-note.md
> Add debugger release notes for 2201.0.3

- release-notes/swan-lake-2201.0.3-release-note.md
> Update debugger release notes for 2201.0.3

- .github/workflows/daily-full-build-patch.yml
> Enable tests in daily full build (patch branch)

- dependabot/build_stdlibs_for_lang_updates.py
> Fix dependecies issue

- release-notes/swan-lake-2201.1.0-release-note.md
Create the 2201.1.0 (Swan Lake) release note. …
> Create the 2201.1.0 (Swan Lake) Release Note

- dependabot/build_stdlibs_for_lang_updates.py
> Fix delete command

- dependabot/build_stdlibs_for_lang_updates.py
> Fix changing versions in pipeline for distribution

- delete-packages-scripts/usernames_with_package_delete_access.json
> Get package delete access

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
Add Async Api tool to the Ballerina release
PR sent to ballerina-distribution master: https://github.com/ballerina-platform/ballerina-distribution/pull/2628
> Add asyncapi module

- .github/workflows/daily-full-build-master.yml
- dependabot/build_stdlibs_for_lang_updates.py
> Enable tests in daily full build (master)

- dependabot/full_build_pipeline_for_updated_stages.py
> Use master branch for transaction module in full build pipeline (patch branch)

- dependabot/full_build_pipeline_for_updated_stages.py
> Enable distribution tests

- ballerinaByExample/templates/example-temp.tmpl
Remove BBE property from the next/previous links.
> Link(s) to product documentation that addresses the changes of this PR. If …
> Remove BBE Property

- .github/workflows/daily-full-build-master.yml
> Change master full build lang branch to 2201.1.0-stage

- .github/workflows/full_build_pipeline_for_updated_stages.yml
> Pass dev central access token to full build

- dependabot/sync_lang_master_with_patch.py
> Switch 2201.0.x to 2201.1.x for master bump
> Switch 2201.0.x to 2201.1.x for master bump

- dependabot/full_build_pipeline_for_updated_stages.py
> Increase heap size for c2c module

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Skip tests for graphql module

- dependabot/sync_lang_master_with_patch.py
To avoid restoring the same branch
> Add timestamp in temp branch

- dependabot/build_stdlibs_for_lang_updates.py
> Add ballerinax modules to full build pipeline

- dependabot/build_stdlibs_for_lang_updates.py
> Enable c2c tests

- dependabot/sync_lang_master_with_patch.py
> Fix PR validating order

- dependabot/build_stdlibs_for_lang_updates.py
> Disable kafka tests

- release-notes/swan-lake-2201.1.0-release-note.md
> Add WebSocket content to the release note

- release-notes/swan-lake-2201.1.0-release-note.md
> Update release note with GraphQL changes

- release-notes/swan-lake-2201.1.0-release-note.md
> Update 2201.1.0 release note with security related changes

- release-notes/swan-lake-2201.1.0-release-note.md
> Update debugger release notes for 2201.1.0

- release-notes/swan-lake-2201.1.0-release-note.md
> Update release note with WebSub related changes

- release-notes/swan-lake-2201.1.0-release-note.md
> Update release note with kafka, ftp, rabbitmq, nats changes

- release-notes/swan-lake-2201.1.0-release-note.md
> Add release notes related to Balllerina AsyncAPI tool
> Update `release-notes/swan-lake-2201.1.0-release-note.md` file
> Add release notes for AsyncAPI tool

- release-notes/swan-lake-2201.1.0-release-note.md
> Update standard library DIU release notes

- release-notes/swan-lake-2201.1.0-release-note.md
> Add gRPC bug fixes for the update 1 release note

- release-notes/swan-lake-2201.1.0-release-note.md
> Add cloud related release notes

- dependabot/build_stdlibs_for_lang_updates.py
> Skip tests for oracledb module

- release-notes/swan-lake-2201.1.0-release-note.md
> Refactor deployment related release notes

- release-notes/swan-lake-2201.1.0-release-note.md
> Add jballerina runtime changes to update 1 release note

- dependabot/build_stdlibs_for_lang_updates.py
> Remove extended libraries from full build

- release-notes/swan-lake-2201.1.0-release-note.md
> Add FE features, improvements and bug fixes to 2201.1.0 Release note

- dependabot/full_build_pipeline_for_updated_stages.py
> Disable tests for http module in patch full build

- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Add installer tests for daily full build (master)

- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Add workflow job name

- dependabot/update_dependencies_in_pipeline.py
> Fix identifying relevant PR when skipiing lang update

- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Fix centos container in full build pipeline

- dependabot/full_build_pipeline_for_updated_stages.py
> Change branch for transaction module

- .github/workflows/sync_dev_and_staging_central_on_release.yml
> The distribution download links used in the dev and staging central workflows has been updated, and the input parameters have been updated to allow the user to trigger the syncup in isolated environments.
> [Central Workflows] Update distribution download link and workflow inputs

- release-notes/swan-lake-2201.0.4-release-note.md
Add the 2201.0.4 release note. …
> Add the 2201.0.4 Release Note

- .github/workflows/delete_stdlibs_staging-central.yml
- .github/workflows/sync_dev_and_staging_central_on_release.yml
- dependabot/delete_staging_central_stdlibs.bal
- dependabot/sync_dev_and_staging_central.bal
> Refactors the delete stdlibs from staging central workflow to trigger delete from registry.
> [Central Workflows] Refactor delete stdlibs from staging central workflow

- dependabot/full_build_pipeline_for_updated_stages.py
> Change branch for websubhub module

- release-notes/swan-lake-2201.0.4-release-note.md
> Update release note with `info`

- dependabot/resources/extensions.json
> [Automated] Update Extensions Dependencies

- ballerinaByExample/tools/generate.go
Resolves ballerina-platform/ballerina-dev-website#4361
> Link(s) to product documentation that addresses the changes of this …
> BBE generation go script update

- .github/workflows/sync_dev_and_staging_central_on_release.yml
> Fixes the dev-central push failure and formats the presentation of the responses printed on the shell.
> Fix dev-central API call and format responses

- .github/workflows/daily-full-build-2201.0.x.yml
- .github/workflows/daily-full-build-2201.1.x.yml
- dependabot/notify_full_build_failure.py
> Add full build pipeline for 2201.1.x

- .github/workflows/daily-full-build-2201.0.x.yml
- .github/workflows/daily-full-build-2201.1.x.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
- dependabot/full_build_pipeline_for_updated_stages.py
> Fix patch full build failure

- dependabot/full_build_pipeline_for_updated_stages.py
> Change mime module branch

- .github/workflows/delete_stdlibs_staging-central.yml
> [Stdlibs Workflow] Refactor delete workflow input description and curl command

- .github/workflows/delete_stdlibs_staging-central.yml
> Fix token for delete stdlibs workflow

- dependabot/full_build_pipeline_for_updated_stages.py
> Change branch for http module

- .github/workflows/sync_lang_master_with_patch.yml
> Add repository owner validation

- dependabot/sync_lang_master_with_patch.py
> Increase API syncing timeout

- dependabot/delete_staging_central_stdlibs.bal
- dependabot/sync_dev_and_staging_central.bal
> [StdLib Workflows] Handle openapi-tools name conflict

- .github/workflows/update_lang_version.yml
Add Python Cryptography module
> Add missing python module

- release-notes/release-note-templates/swan-lake-patch-release-note-template.md
- release-notes/swan-lake-release-notes/swan-lake-2201.1.1-release-note.md
Add the 2201.1.1 release note. …
> Add the 2201.1.1 Release Note

- dependabot/update_lang_version.py
> Remove redundant argument specification

- dependabot/update_lang_version.py
> Fix committing branch

- .github/workflows/daily-full-build-2201.2.x.yml
> Add daily full build for 2201.2.x branch

- .github/workflows/daily-full-build-2201.2.x.yml
> Fix notification links

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
Add the 2201.2.0 release note. …
> Add the Swan Lake 2201.2.0 Release Note

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add graph, include to release-notes

- release-notes/swan-lake-release-notes/swan-lake-2201.1.1-release-note.md
> Add Bug fixes link to Lang issue page in release note

- dependabot/resources/module_list.json
> $ Subject
Related issue: [#3075](https://github.com/ballerina-platform/ballerina-standard-library/issues/3075)
> Link to the PR …
> Add module-ballerina-serdes to module_list.json

- dependabot/generate-build-time-stats.py
> Add python script to send and merge PR

- .github/workflows/generate-build-time-stats.yml
> Modify workflow to send PRs

- .github/workflows/daily-full-build-2201.2.x.yml
> Change branch to 2201.2.0-stage

- .github/workflows/full_build_pipeline.yml
- dependabot/full_build_pipeline_for_updated_stages.py
Serdes module was added with the `2201.2.0 (Swan Lake Update 2)` release. …
> Skip serdes module for 2201.1.x and 2201.0.x builds

- dependabot/build_stdlibs_for_lang_updates.py
> Increase heap space for http module

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add GraphQL Release Notes

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
- dependabot/resources/full_build_ignore_modules.json
`module-ballerina-constraint` and `module-ballerina-serdes` has been added along with `2201.2.0` and those modules cannot be built with `2201.0.x` or `2201.1.x`.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Ignore some modules in 2201.0.x and 2201.1.x full builds

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Fix reading ignore modules

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
- dependabot/resources/full_build_ignore_modules.json
> Skip http tests temporary

- .github/workflows/trigger-ballerinax-connectors-build.yml
> Update triggerballerinax-connectors-build to trigger daily

- dependabot/update_lag_status.py
> Disable lag status calculation as this is not used

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add constraint package to 2201.2.0 release note

- dependabot/full_build_pipeline_for_updated_stages.py
> Change branch for c2c module in 2201.1.x full build pipeline

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add semver validator tool release notes

- .github/workflows/notify-build-failures.yml
- dependabot/notify_build_failure.py
Currently there are some repos such as `ballerina-distribution` which is running daily builds for multiple branches. We need to specify the branch as well along with repository name. 
This will check whether we have given branch name as payload or not. If branch name has given, then it will notify in the chat the repository name as well as the branch name. Otherwise it will only notify repository name as usual.
https://github.com/ballerina-platform/ballerina-distribution/issues/2943
> Link to the …
> Notify build failures specifying branch

- release-notes/swan-lake-release-notes/swan-lake-2201.1.2-release-note.md
Add the 2201.1.2 release note. …
> Add the 2201.1.2 release note

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add c2c update 2 release notes

- release-notes/swan-lake-release-notes/swan-lake-2201.1.2-release-note.md
Add CLI and ProjectAPI bug fix github URLs to 2201.1.2 release note.
> Add CLI and ProjectAPI bug fixes

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Update release note with OpenAPI Tool changes

- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add OS and Random module changes to 2201.2.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
Add LS release note for the 2201.2.0 release. …
> Add LS changes to 2201.2.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Add Compiler API related changes in the 2201.2.0 release note. …
> Add Compiler API related updates in 2201.2.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Add io package changes to 2201.2.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add xmldata package changes to 2201.2.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Add HTTP changes to 2201.2.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Address the review suggestions of https://github.com/ballerina-platform/ballerina-release/pull/2090#discussion_r945949385
> …
> Update Compiler API content in release note 2201.2.0

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
Fix LS release note for the 2201.2.0 release. …
> Fix LS changes in the release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Add language changes to the release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2202.2.0-release-note.md
> Add runtime changes to 2201.2.0 release note

- dependabot/resources/extensions.json
- test-scripts/ballerina-test-automation/.settings/org.eclipse.buildship.core.prefs
> Update the dependency level for ballerina-log module

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Update release note with gRPC, Kafka, RabbitMQ, NATS updates

- release-notes/swan-lake-release-notes/swan-lake-2201.1.2-release-note.md
> Update release note for 2201.1.2

- release-notes/swan-lake-release-notes/swan-lake-2201.1.2-release-note.md
> Update Standard library issue link

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
$title, since the PR is being reverted for update 2.
> Remove the narrowing change from the release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.0-release-note.md
> Improve terms used in the release note for `isolated` feature

- .github/workflows/trigger-ballerinax-connectors-build.yml
$title
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Check actor when triggering ballerinax connectors build

- test-scripts/ballerina-central/tests/run-tests.sh
> Remove outdated tests for alpha5 and beta1 versions

- .github/workflows/daily-full-build-2201.2.x.yml
- dependabot/resources/full_build_ignore_modules.json
> Change branch after 2201.2.0 release

- .github/workflows/daily-full-build-2201.2.x.yml
> Add ballerina patch level as 2201.1.x

- .github/workflows/full_build_pipeline_for_updated_stages.yml
- dependabot/full_build_pipeline_for_updated_stages.py
> Add 2201.2.x patch level for full build pipeline (on demand)

- release-notes/swan-lake-release-notes/swan-lake-2201.2.1-release-note.md
Add the Swan Lake 2201.2.1 release note. …
> Add the Swan Lake 2201.2.1 release note

- dependabot/notify_build_failure.py
> Update chat message for repos without code owners

- dependabot/notify_full_build_failure.py
$subject.
Fixes https://github.com/ballerina-platform/ballerina-release/issues/2130 …
> Fix daily full build failure notifications for empty codeowner files

- .github/workflows/notify-build-failures.yml
> Fix a minor issue

- .github/workflows/daily-full-build-2201.3.x.yml
- dependabot/resources/full_build_ignore_modules.json
> Add full build pipeline for 2201.3.x

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
Create the 2201.3.0 release note. …
> Create the 2201.3.0 release note

- test-scripts/ballerina-central/tests/run-tests.sh
> Remove outdated tests for beta2 versions

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
> $Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3484
> Add Persist module and Persist tool to release

- dependabot/full_build_pipeline_for_updated_stages.py
> Change checkout branch for c2c

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Add no-daemon with gradle build

- dependabot/resources/full_build_ignore_modules.json
> Remove persist module from 0.x, 1.x and 2.x build pipelines

- release-notes/swan-lake-release-notes/swan-lake-2201.2.2-release-note.md
Add the 2201.2.2 release note. …
> Add the 2201.2.2 release note

- dependabot/notify_build_failure.py
- dependabot/notify_full_build_failure.py
> Change build failure notification tagging

- .github/workflows/code-cov.yml
- .github/workflows/daily-full-build-2201.1.x.yml
- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/trigger-ballerinax-connectors-build.yml
> Change time zone for scheduled jobs

- release-notes/swan-lake-release-notes/swan-lake-2201.2.3-release-note.md
Create the 2201.2.3 release note. …
> Create the 2201.2.3 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.3-release-note.md
> Remove Project API and CLI from bug fixes
> Remove Project API and CLI from bug fixes

- release-notes/swan-lake-release-notes/swan-lake-2201.2.3-release-note.md
> Add LS new features to 2201.2.3 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.2.3-release-note.md
> Update SL 2201.2.3 release note for std-lib bug fixes

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Update gRPC changes in the release note

- .github/workflows/daily-full-build-master.yml
> Update downstream repo branch

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Update release-note with GraphQL Changes

- release-notes/swan-lake-release-notes/swan-lake-2201.2.3-release-note.md
> Update release note with OpenAPI changes

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Update release notes with native-image info

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Add runtime changes to 2201.3.0 release note

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Update release-note with Graphql Tool changes

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Update release note with HTTP updates

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
$Subject.
Took the c2c section below near devtools updates section as the c2c feature also is related --native feature discussed in devtools section. 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
> Add update 3 c2c release note

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
$subject
- Semantic API: [https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aissue+is%3Aclosed+label%3AArea%2FSemanticAPI+milestone%3A2201.3.0](https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aissue+is%3Aclosed+label%3AArea%2FSemanticAPI+milestone%3A2201.3.0) 
- Lang Server: [https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aissue+is%3Aclosed+milestone%3A2201.3.0+label%3ATeam%2FLanguageServer](https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aissue+is%3Aclosed+milestone%3A2201.3.0+label%3ATeam%2FLanguageServer)
> Add Semantic API and Language server updates to release note of 2201.3.0

- release-notes/release-note-templates/swan-lake-patch-release-note-template.md
- release-notes/swan-lake-release-notes/swan-lake-2201.1.1-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2201.1.2-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2201.2.1-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2201.2.2-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2201.2.3-release-note.md
- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
Fix the troubleshooting links in the release notes. …
> Fix the troubleshooting links in the release notes

- dependabot/build_stdlibs_for_lang_updates.py
> Fix installer tests failure in FBP

- .github/workflows/daily-full-build-master.yml
> Add nballerina tests to full build pipeline

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> [2201.3.0] Remove OpenAPI IDL details from release note 

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Remove IDL support related features

- .github/workflows/daily-full-build-master.yml
> Fix Full Build Pipeline (master)

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
$subject
Include a note on a known bug in the graalVM native image build.
> Type “Sent” when you have provided new/updated …
> Include a note on a known bug in graalVM

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Add language updates to release note of 2201.3.0

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Run project-api tests seperately in FBP

- release-notes/swan-lake-release-notes/swan-lake-2201.3.0-release-note.md
> Add outer join breaking change

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Nballerina build fix

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
> Fix installer tests failure

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
> Set dotnet-guid version

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
> Fix distribution path issue

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Set java version in installer tests

- .github/workflows/daily-full-build-master.yml
$subject
This was swithed  temporarily till SW Update3 release in https://github.com/ballerina-platform/ballerina-release/pull/2177
> Switch to master branch for daily build pipeline

- dependabot/resources/full_build_ignore_modules.json
> $Subject
Fix for daily build failure …
> Change the build branch for OpenAPI repository

- dependabot/resources/full_build_ignore_modules.json
> Add grpc build branch

- dependabot/resources/full_build_ignore_modules.json
> Ignore persist modules for 2x and 3x lang build

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-master.yml
> Fix notification for nballerina build

- dependabot/resources/module_list.json
> Fix version key of persist tools

- .github/workflows/daily-full-build-2201.2.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-master.yml
> Set java version to 11

- .github/workflows/pipeline_for_module_testing.yml
- dependabot/pipeline_for_module_testing.py
$subject
Increase testability among standard library modules.
> Add pipeline for module testing

- .github/workflows/daily-full-build-2201.4.x.yml
> Add Full Build Pipeline for 2201.4.x

- .github/workflows/daily-full-build-2201.4.x.yml
- dependabot/pipeline_for_module_testing.py
> Fix notification for 2201.4.x

- dependabot/resources/full_build_ignore_modules.json
- dependabot/resources/module_list.json
> Add ballerina-dev-tools to FBP

- dependabot/resources/module_list.json
> Fix build bage url

- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-master.yml
> Setup nodejs version for FBP

- dependabot/resources/extensions.json
> Remove observe module

- dependabot/resources/extensions.json
> Remove balleriani observe module

- dependabot/resources/extensions.json
> Remove extended libraries and non stdlib repos

- dependabot/resources/extensions.json
> Add persist-tools to extentions.json

- dependabot/build_stdlibs_for_lang_updates.py
> Set distribution branch name

- dependabot/build_stdlibs_for_lang_updates.py
> Fix getting distribution branch name

- dependabot/resources/extensions.json
> Update extentions.json for lang rc2 update

- .github/workflows/sync_dev_and_staging_central_on_release.yml
> Improve 'sync stdlibs to staging and dev' workflow to fail when upload fails

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Change lang version for installer tests in FBP

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Update method of setting up installer test version

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Remove setting up installer test version

- .github/workflows/daily-full-build-2201.4.x.yml
> Change lang branch in FBP 2201.4.x

- .github/workflows/full_build_pipeline.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
- .github/workflows/pipeline_for_module_testing.yml
> Set up nodejs version

- dependabot/resources/full_build_ignore_modules.json
> Specify branches for dev-tools in FBP

- dependabot/notify_build_failure.py
> Update notification chat code to handle trivy scan failure notification

- .github/workflows/notify-build-failures.yml
> Add Notify trivy failure type to repository dispatches

- .github/workflows/daily-full-build-2201.5.x.yml
> Add new FBP for 2201.5.x

- dependabot/resources/full_build_ignore_modules.json
> Skip persist modules

- .github/workflows/update_dependency_graph.yml
> Update schedule time to midnight LK

- dependabot/resources/extensions.json
Reverts ballerina-platform/ballerina-release#2301
> Revert "[Automated] Update Extensions Dependencies"

- delete-packages-scripts/usernames_with_package_delete_access.json
> Adding Self to Package Delete Permits

- .github/workflows/daily-full-build-master.yml
> Increase timeout

- dependabot/resources/module_list.json
Update module_list.json with math.vector package
> Update module_list.json with math.vector package

- dependabot/resources/extensions.json
Move math.vector from extended library to standard library and lower level.
> Move math.vector from extended library to standard library

- .github/workflows/daily-full-build-2201.5.x.yml
> Increase the timout

- dependabot/resources/full_build_ignore_modules.json
> Update dev-tools branch for 2201.4.x full-build-pipeline

- dependabot/build_stdlibs_for_lang_updates.py
- dependabot/full_build_pipeline_for_updated_stages.py
> Delete module after build

- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
> Change branch for installer build in FBP(2201.4.x)

- dependabot/resources/full_build_ignore_modules.json
> Update full build ignore modules json

- .github/workflows/daily-full-build-2201.4.x.yml
> Skip dev tools tests related to Architecture model generator
> Skip dev tools tests

- .github/workflows/daily-full-build-2201.5.x.yml
> Fix running installers against master branch
> Fix running installer tests against master branch

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-master.yml
Reverts ballerina-platform/ballerina-release#2337 as issue ballerina-platform/nballerina#1201 is now fixed.
> Revert "Temporary disable nballerina longRunning tests"

- dependabot/resources/full_build_ignore_modules.json
$subject
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question …
> Add downstream branch for 5.x in dev-tools

- dependabot/resources/full_build_ignore_modules.json
Since there  is an intermittent test failure, the dev-tools tests are disabled for 5.x branch
> Link to the PR for changes to the …
> Disable tests of dev-tools for 5.x branch

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
> Change file path for build script

- dependabot/resources/full_build_ignore_modules.json
Reverts ballerina-platform/ballerina-release#2358
> Revert "Disable tests of dev-tools for 5.x branch"

- dependabot/full_build_pipeline.py
> Fix creating failed-modules.txt

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
> Fix notify build failures

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-master.yml
> Divide FBP(master) into 3 jobs

- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
> Add new FBP for update 6

- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
> Fix downloading artifacts

- dependabot/full_build_pipeline.py
> Add no-daemon for lang build

- dependabot/full_build_pipeline.py
> Disable bbe tests in distribution

- .github/workflows/full_build_pipeline.yml
> Divide FBP(manual trigger) into 3 jobs

- dependabot/resources/module_list.json
> Related to
https://github.com/ballerina-platform/ballerina-standard-library/issues/4395
https://github.com/ballerina-platform/ballerina-standard-library/issues/4394
> Add yaml and toml modules to the release

- dependabot/resources/module_list.json
> Include EDI module to Ballerina release
> Include EDI module to Ballerina release

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Change distribution level

- dependabot/resources/full_build_ignore_modules.json
> Skip building toml, yaml modules in older FBP

- dependabot/resources/module_list.json
$title
Related to:
https://github.com/ballerina-platform/ballerina-standard-library/pull/4472
https://github.com/ballerina-platform/ballerina-standard-library/issues/4471
> Remove stan module from daily build pipeline

- dependabot/resources/full_build_ignore_modules.json
> Update FBP with OpenAPI repo branches

- .github/workflows/daily-full-build-2201.6.x.yml
> Change lang branch for 2201.6.x FBP

- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
> Add MacOS ARM installer build in FBP

- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
> Fix downloading MacOS-ARM zip

- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
$subject
Related Issue - #2403
> Remove MacOS-ARM installer tests

- dependabot/full_build_pipeline.py
> Fix log in FBP

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
> Fix checking out distribution branch in windows

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
$title
nBallerina has a set of "private" tests not meant to be run by outside users.
> Disable nBallerina private tests

- dependabot/full_build_pipeline.py
> Include checking out for timestamp release stages

- dependabot/full_build_pipeline.py
> Fix error in FBP

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
Fix full build pipeline failure in `master` & `2201.6.x` branches due to the maximum disk space usage
> Add remove-after-build flag

- dependabot/resources/module_list.json
> Add edi properties

- .github/workflows/daily-full-build-2201.6.x.yml
> Change 2201.6.x build to build released versions

- dependabot/resources/full_build_ignore_modules.json
> Fix FBP ignore modules json file

- .github/workflows/full_build_pipeline.yml
> Update distribution level in FBP

- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Add secrets for persist-tool tests

- .github/workflows/daily-full-build-2201.7.x.yml
> Add Full Build Pipeline for 2201.7.x

- dependabot/resources/full_build_ignore_modules.json
> Include build ignore modules in json for 2201.7.x

- dependabot/resources/extensions.json
> Update persist module level

- dependabot/resources/extensions.json
> Update extension file

- dependabot/full_build_pipeline.py
> Fix stdlib dependencies are updating in distribution

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
- .github/workflows/notify-build-failures.yml
- .github/workflows/pipeline_for_module_testing.yml
> Migrate to Java 17

- dependabot/resources/module_list.json
> Add persist modules in the module list

- dependabot/full_build_pipeline.py
> Fix using downstream branch in FBP

- delete-packages-scripts/usernames_with_package_delete_access.json
> Update usernames with delete package access

- .github/workflows/full_build_pipeline.yml
> Update distribution level

- .github/workflows/full_build_pipeline.yml
> Remove installer tests

- .github/workflows/full_build_pipeline.yml
Reverts ballerina-platform/ballerina-release#2475
> Revert "Remove installer tests"

- dependabot/resources/module_list.json
> Remove regex module from release pipeline

- .github/workflows/notify-simulator-failure.yml
> Fix LS simulator notification failure

- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Update Java version to Java 17.0.7

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-master.yml
> Update target Java versions of daily full-build workflows

- .github/workflows/full_build_pipeline.yml
> Change full-build target branches back to patch branch

- .github/workflows/notify-simulator-failure.yml
- dependabot/notify_simulator_failure.py
> Refactor simulator failure notification to use JDK17

- .github/workflows/daily-full-build-2201.7.x.yml
> Update FBP for 2201.7.x

- dependabot/resources/full_build_ignore_modules.json
> Update ignore modules for 2201.7.x FBP

- dependabot/resources/full_build_ignore_modules.json
> Update openAPI and dev-tools repo branches in 2201.7.x FBP

- dependabot/resources/module_list.json
> Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4714
> Add soap module to the release

- dependabot/resources/extensions.json
> Update SOAP module level in extensions.json file

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
> Update properties for Soap module in module list

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
> Add `mqtt` to ballerina release

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
> Add `java.jms` to ballerina release

- dependabot/resources/module_list.json
> Update module list with more details of mqtt module

- .github/workflows/daily-full-build-2201.8.x.yml
> Add FBP for 2201.8.x

- dependabot/full_build_pipeline.py
> Fix checkout to defined branches in FBP

- dependabot/full_build_pipeline.py
> Fix checkout to defined branches

- .github/workflows/full_build_pipeline.yml
> Add 2201.8.x patch level to FBP

- .github/workflows/daily-full-build-2201.8.x.yml
> Update daily-full-build-2201.8.x.yml to use java17

- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-master.yml
> Update distribution level in 8.x fbp

- .github/workflows/trigger-ballerinax-connectors-build.yml
> Fix post req path in connector build

- .github/workflows/full_build_pipeline.yml
> Update FBP manual trigger to detect java version

- .github/workflows/full_build_pipeline.yml
> Fix FBP manual trigger

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
> Remove soap module dependency

- dependabot/resources/full_build_ignore_modules.json
> Update GraphQL Tool Downstream Branches

- CONTRIBUTING.md
> Add contributing guide for Ballerina release

- CONTRIBUTING.md
> Fix Contributing.md

- dashboard/index.html
- dependabot/pipeline_for_module_testing.py
- dependabot/update_stdlib_dependency_graph.py
Update the `ballerina library` word. …
> Update the `ballerina library` word

- dependabot/update_dependencies_in_pipeline.py
- dependabot/update_lag_status.py
Change the term `extended library` to `Ballerina library`. …
> Change the term `extended library` to `Ballerina library`

- delete-packages-scripts/usernames_with_package_delete_access.json
> Update delete access permissions

- dependabot/resources/full_build_ignore_modules.json
> Skip npmTestDocerinaUI in dev-tools (2201.4.x)

- .github/workflows/daily-full-build-2201.8.x.yml
> Update 2201.8.x Daily Full Build

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
> Temporarily disable 3.x to 6.x full build pipelines

- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-master.yml
> Disable Daily Full Builds

- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
Reverts ballerina-platform/ballerina-release#2584
> Revert "Temporarily disable 3.x to 6.x full build pipelines"

- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-master.yml
Reverts ballerina-platform/ballerina-release#2586
> Revert "Disable Daily Full Builds"

- central_stats/main.bal
- https://github.com/ballerina-platform/ballerina-central/issues/95
> Use appendValues for data writing 

- central_stats/Dependencies.toml
- central_stats/main.bal
- https://github.com/ballerina-platform/ballerina-central/issues/95
> Update the dependencies

- .github/workflows/ballerina-central-stats.yml
- https://github.com/ballerina-platform/ballerina-central/issues/95
> Update the Ballerina Version

- delete-packages-scripts/usernames_with_package_delete_access.json
Add release manages to the package delete permission list.
> Update package delete permissions for release managers

- central_stats/main.bal
- Update date format to MM/DD/YYYY
- https://github.com/ballerina-platform/ballerina-release/issues/2619
> Update date format to MM/DD/YYYY in Central Stats

- central_stats/main.bal
- Add debug logs to central stats
> Add debug logs to central stats

- dependabot/resources/full_build_ignore_modules.json
> $subject
Part of: [#6041](https://github.com/ballerina-platform/ballerina-library/issues/6041)
> Skip websub tests in 2201.8.x full-build workflow

- central_stats/main.bal
- https://github.com/ballerina-platform/ballerina-library/issues/6039
> Set value valueInputOption to USER_ENTERED in central stat gen

- dependabot/resources/full_build_ignore_modules.json
> $subject
Part of: https://github.com/ballerina-platform/ballerina-library/issues/6041
> Skip tests for websub module

- dependabot/resources/module_list.json
> Add jsondata and xmldata to daily build pipeline

- dependabot/resources/extensions.json
> Update the level of jsondata and xmldata

- .github/workflows/full_build_pipeline.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
> Enable Ballerina central verbose mode
> Enable Ballerina central verbose mode

- .github/workflows/daily-full-build-2201.9.x.yml
> Add FBP for 2201.9.x

- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-2201.9.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
- dependabot/full_build_pipeline.py
> Update full build pipeline

- dependabot/resources/module_list.json
> Add Avro module to daily build pipeline 

- .github/workflows/daily-full-build-2201.9.x.yml
> Update lang branch in 2201.9.x FBP

- dependabot/update_dependencies_in_pipeline.py
> Fix PR build check

- dependabot/resources/extensions.json
> Add udp module to the list

- dependabot/update_dependencies_in_pipeline.py
> Improve Standard library dependency update workflow

- .github/workflows/daily-full-build-2201.9.x.yml
- dependabot/full_build_pipeline.py
> Remove used docker containers after module builds

- dependabot/full_build_pipeline.py
> Update FBP script

- .github/workflows/trigger-ballerinax-connectors-build.yml
$subject.
Resolves https://github.com/ballerina-platform/ballerina-library/issues/6537
> Link to the PR for changes to the …
> Disable daily repository dispatch event trigger for connectors

- dependabot/resources/full_build_ignore_modules.json
> Disable oauth2 module test cases

- .github/workflows/delete-package.yml
> $title, it enables to delete many packages at once when we provide a comma separated list of packages.
> Link to the PR for …
> Enable Delete Package workflow to delete many packages

- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-2201.9.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
> Setup graalvm for FBP

- dependabot/resources/module_list.json
> Add data.yaml module to module list

- .github/workflows/daily-full-build-2201.10.x.yml
> Add FBP for 2201.10.x

- .github/workflows/full_build_pipeline.yml
> Add 2201.10.x branch to full build

- dependabot/resources/full_build_ignore_modules.json
> Update Downstream Repo Branch for Auth Module

- dependabot/resources/module_list.json
> Add LDAP module to daily-build pipeline

- dependabot/resources/module_list.json
> Update `group_id` for the ldap package

- dependabot/resources/extensions.json
> Update LDAP package details in the extensions.json

- dependabot/resources/extensions.json
- dependabot/resources/module_list.json
> [2201.10.x] Add ldap module details

- dependabot/resources/full_build_ignore_modules.json
> Update FBP ignore modules json

- dependabot/resources/full_build_ignore_modules.json
> [2201.10.x] Update FBP ignore modules json

- .github/workflows/full_build_pipeline.yml
> Remove 2201.10.x branch from patch level options

- dependabot/resources/full_build_ignore_modules.json
> Update U8 full-build branch for MQTT

- dependabot/resources/full_build_ignore_modules.json
> Update http branch for U8 and U9 daily builds

- dependabot/resources/full_build_ignore_modules.json
> Update gRPC branch for U8 and U9 daily builds

- dependabot/resources/full_build_ignore_modules.json
> Update U9 full-build branch for MQTT

- .github/workflows/daily-full-build-2201.10.x.yml
> Update FBP (2201.10.x)

- .github/workflows/daily-full-build-2201.10.x.yml
- .github/workflows/daily-full-build-2201.3.x.yml
- .github/workflows/daily-full-build-2201.4.x.yml
- .github/workflows/daily-full-build-2201.5.x.yml
- .github/workflows/daily-full-build-2201.6.x.yml
- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-2201.9.x.yml
- .github/workflows/daily-full-build-master.yml
- .github/workflows/full_build_pipeline.yml
- .github/workflows/full_build_pipeline_for_updated_stages.yml
> Update the deprecated download artifact action version to v4

- dependabot/resources/module_list.json
Add csv data library to the daily full build pipeline
> Add csv data library to the daily full build pipeline

- .github/workflows/full_build_pipeline.yml
> Update Full Build Pipeline with Java version changes

- .github/workflows/full_build_pipeline.yml
- dependabot/resources/full_build_ignore_modules.json
> Update daily builds

- .github/workflows/daily-full-build-2201.11.x.yml
- .github/workflows/daily-full-build-master.yml
> Add FBP for 2201.11.x

- dependabot/resources/module_list.json
Update version key for tools according to the https://github.com/ballerina-platform/ballerina-distribution/blob/master/gradle.properties.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
> Update version key for tools

- dependabot/resources/module_list.json
> Change the version key of jsondata module

- .github/workflows/daily-full-build-2201.10.x.yml
- .github/workflows/daily-full-build-2201.7.x.yml
- .github/workflows/daily-full-build-2201.8.x.yml
- .github/workflows/daily-full-build-2201.9.x.yml
- dependabot/resources/full_build_ignore_modules.json
> Specify observe module branches

- dependabot/resources/full_build_ignore_modules.json
> Temporary disable graphql tests for 2201.10.x FBP

- dependabot/resources/module_list.json
> Add the np module to the module list

- dependabot/resources/module_list.json
> Explicitly set is_extended_library_module to false for np

- dependabot/resources/full_build_ignore_modules.json
> Ignore the np module build on 2201.12.x

- dependabot/resources/module_list.json
> Add ai module

- dependabot/resources/extensions.json
> Update graphql-tool in extensions.json file
> Update graphql-tool in extensions.json file

- dependabot/resources/extensions.json
> Fix `protoc-tools` module name

- dependabot/resources/module_list.json
> Set version key for ai.np

- dependabot/resources/extensions.json
> Update grpc, graphql, and grpc tools for decoupling
> Update grpc, graphql, and openapi tools for decoupling

- dependabot/resources/extensions.json
> Update asyncapi and openapi tools for decoupling
